### PR TITLE
Set raw description message format to string when using string state…

### PR DESCRIPTION
**Pull request by akilaw**
When conf.sqlServerBinaryTransferMode is false go language postgre library failed to work. Reason for this was raw description format code was set to binary without considering the conf.sqlServerBinaryTransferMode flag. 

This pull request fix that issue.

### CODE REVIEW

**Comment by maropu** [comment]
Thanks for you interest! I'll check tonight, then merge this.

**Comment by akilaw** [comment]
Fixed formatting issues.

**Comment by maropu** [comment]
Thanks! merged to master

**Comment by maropu** [comment]
aha, looks great! If you find bugs or some issues, it'd be nice to put them in the issue tracker or make PRs. Thanks!

**Pull request merged**
